# Generated by Django 4.1.7 on 2023-11-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logInjestor', '0003_logentry_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='metadata',
        ),
    ]
