# Generated by Django 4.1.7 on 2023-11-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logInjestor', '0004_remove_logentry_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='parentResourceId',
            field=models.CharField(max_length=40),
        ),
    ]
